{% load_yaml as lookup %}
FreeBSD:
    ntpd_service: ntpd
    ntpdate_service: ntpdate
    config_file: /etc/ntp.conf
Debian:
    package: ntp
    ntpd_service: ntp
    config_file: /etc/ntp.conf
CentOS:
    package: ntp
    ntpd_service: ntpd
    config_file: /etc/ntp.conf
{% endload %}

{% load_yaml as rawmap %}
timezone: Europe/Paris
{% endload %}
